### PR TITLE
updated alpine to edge, php to 7.4 and nginx to 1.19.5

### PR DESCRIPTION
**Pull request by Apfelwurm**
updated alpine to edge, php to 7.4 and nginx to 1.19.5

### CODE REVIEW

**Comment by th0rn0** [comment]
All looks good - any reason for using edge? Is it just for the APK repo?

**Comment by Apfelwurm** [comment]
Jep, i was to lazy to look into getting all the packages from Outside the alpine repo and i didn't want to install edge packages into 3.12 :D i have wrote you an mail yesterday about this PR and a few other things :)

**Comment by th0rn0** [comment]
> i have wrote you an mail yesterday about this PR and a few other things :)

Odd I havent recieved anything. Mind sending it again and I'll look at getting this merged tonight for you

**Comment by Apfelwurm** [comment]
> > i have wrote you an mail yesterday about this PR and a few other things :)
> 
> Odd I havent recieved anything. Mind sending it again and I'll look at getting this merged tonight for you

Strange :O I have sent it again :) No need to do it fast, our dev version temporary uses our dockerfile. Have a great day! :)

**Pull request merged**
